/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jutils_platform_jni_JniSerialPort */

#ifndef _Included_jutils_platform_jni_JniSerialPort
#define _Included_jutils_platform_jni_JniSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniSerialPort_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    register
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_jutils_platform_jni_JniSerialPort_register
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniSerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniSerialPort_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    getConfig
 * Signature: (Ljutils/platform/SerialConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniSerialPort_getConfig
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    setConfig
 * Signature: (Ljutils/platform/SerialConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniSerialPort_setConfig
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    setReadTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jutils_platform_jni_JniSerialPort_setReadTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jutils_platform_jni_JniSerialPort_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     jutils_platform_jni_JniSerialPort
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jutils_platform_jni_JniSerialPort_write
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
