/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jutils_platform_jni_JniPlatform */

#ifndef _Included_jutils_platform_jni_JniPlatform
#define _Included_jutils_platform_jni_JniPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jutils_platform_jni_JniPlatform
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniPlatform_initialize
  (JNIEnv *, jobject);

/*
 * Class:     jutils_platform_jni_JniPlatform
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniPlatform_destroy
  (JNIEnv *, jobject);

/*
 * Class:     jutils_platform_jni_JniPlatform
 * Method:    listPorts
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_platform_jni_JniPlatform_listPorts
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
