/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jutils_serial_JnaSerialPort */

#ifndef _Included_jutils_serial_JnaSerialPort
#define _Included_jutils_serial_JnaSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;Ljutils/serial/JnaPortConfig;)I
 */
JNIEXPORT jint JNICALL Java_jutils_serial_JnaSerialPort_open
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jutils_serial_JnaSerialPort_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    getConfig
 * Signature: (ILjutils/serial/JnaPortConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_serial_JnaSerialPort_getConfig
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    setConfig
 * Signature: (ILjutils/serial/JnaPortConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_serial_JnaSerialPort_setConfig
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    listPorts
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_jutils_serial_JnaSerialPort_listPorts
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_jutils_serial_JnaSerialPort_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     jutils_serial_JnaSerialPort
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_jutils_serial_JnaSerialPort_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
